name: "WowHead Archiver"
on:
  workflow_dispatch:

jobs:
  dl_wowhead:
    runs-on: ubuntu-latest
    steps:
    - name: "Download WowHead"
      continue-on-error: true
      run:  |
        sudo apt-get install wget
        timeout 120 wget -mpEk https://www.wowhead.com/news
    - name: "Upload Artifact"
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: wowhead_retail
        path: |
          ./**/[a-zA-Z0-9+].css
          ./**/[a-zA-Z0-9+].html
          ./**/[a-zA-Z0-9+].js
          ./**/[a-zA-Z0-9+].jpg
          ./**/[a-zA-Z0-9+].png
