name: "WowHead Archiver"
on:
  workflow_dispatch:

jobs:
  dl_wowhead:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: "Download WowHead"
      run:  |
        sudo apt-get install wget
        timeout 120 wget -mpEk https://www.wowhead.com
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: wowhead_ptr
        path: ./
