name: "WowHead Archiver"
on:
  workflow_dispatch:

jobs:
  dl_wowhead:
    runs-on: ubuntu-latest
    steps:
    - name: "Download WowHead"
      run:  |
        sudo apt-get install wget
        wget -rpEk --limit=2 --timeout=120 https://www.wowhead.com
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: wowhead_ptr
        path: ./
